-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/JBSOEM
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.

DROP TABLE IF EXISTS "Crashes";

CREATE TABLE "Crashes" (
    "crashID" int   NOT NULL,
    "crashYear" int   ,
    "region" varchar(100)   ,
    "territoryID" int   ,
    "territorialAuthority" varchar(100)  ,
    "urban" varchar(50)   ,
    "crashLocation1" varchar(100)   ,
    "crashLocation2" varchar(100)   ,
    "latitude" float   ,
    "longitude" float   ,
    "crashDirection" varchar(50),
    "roleDirection" varchar(50),
    "crashSeverity" varchar(50)   ,
    "fatalInjuries" int   ,
    "seriousInjuries" int   ,
    "minorInjuries" int  ,
    "holiday" varchar(50),
    "roadCharacter" varchar(50),
    "roadLanes" varchar(50),
    "numberOfLanes" int ,
    "roadSurface" varchar(50),
    "speedLimit" int ,
    "tempSpeed" int ,
    "trafficControl" varchar(50),
    "roadworks" int ,
    "bicycle" int ,
    "bus" int ,
    "stationWagon" int ,
    "moped" int ,
    "motorcycle" int ,
    "suv" int ,
    "taxi" int ,
    "train" int ,
    "truck" int ,
    "van" int ,
    "utilityVehicle" int ,
    "schoolBus" int ,
    "otherVehicleType" int ,
    "unknownVehicleType" int ,
    "pedestrian" int ,
    "parkedVehicle" int ,
    "bridge" int ,
    "cliffBank" int ,
    "debris" int ,
    "ditch" int ,
    "fence" int ,
    "flatHill" varchar(50) ,
    "guardRail" int ,
    "building" int ,
    "kerb" int ,
    "objectThrown" int ,
    "otherObject" int ,
    "overBank" int ,
    "phoneBox" int ,
    "postOrPole" int ,
    "slipOrFlood" int ,
    "strayAnimal" int ,
    "trafficIsland" int ,
    "trafficSign" int ,
    "tree" int ,
    "river" int ,
    "light" varchar(50) ,
    "streetLight" varchar(50) ,
    "weatherRain" varchar(50) ,
    "weatherWind" varchar(50) ,
    CONSTRAINT "pk_Crashes" PRIMARY KEY (
        "crashID"
     )
);

