-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/JBSOEM
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.

DROP TABLE IF EXISTS 'Crashes';

CREATE TABLE "Crashes" (
    "crashID" int   NOT NULL,
    "crashYear" int   NOT NULL,
    "region" varchar(100)   NOT NULL,
    "territoryID" int   NOT NULL,
    "territorialAuthority" varchar(100)   NOT NULL,
    "urban" varchar(50)   NOT NULL,
    "crashLocation1" varchar(100)   NOT NULL,
    "crashLocation2" varchar(100)   NOT NULL,
    "latitude" float   NOT NULL,
    "longitude" float   NOT NULL,
    "crashDirection" varchar(50)   NOT NULL,
    "roleDirection" varchar(50)   NOT NULL,
    "crashSeverity" varchar(50)   NOT NULL,
    "fatalInjuries" int   NOT NULL,
    "seriousInjuries" int   NOT NULL,
    "minorInjuries" int   NOT NULL,
    "holiday" varchar(50)   NOT NULL,
    "roadCharacter" varchar(50)   NOT NULL,
    "roadLanes" varchar(50)   NOT NULL,
    "numberOfLanes" int   NOT NULL,
    "roadSurface" varchar(50)   NOT NULL,
    "speedLimit" int   NOT NULL,
    "tempSpeed" int   NOT NULL,
    "trafficControl" varchar(50)   NOT NULL,
    "roadworks" int   NOT NULL,
    "bicycle" int   NOT NULL,
    "bus" int   NOT NULL,
    "stationWagon" int   NOT NULL,
    "moped" int   NOT NULL,
    "motorcycle" int   NOT NULL,
    "suv" int   NOT NULL,
    "taxi" int   NOT NULL,
    "train" int   NOT NULL,
    "truck" int   NOT NULL,
    "van" int   NOT NULL,
    "utilityVehicle" int   NOT NULL,
    "schoolBus" int   NOT NULL,
    "otherVehicleType" int   NOT NULL,
    "unknownVehicleType" int   NOT NULL,
    "pedestrian" int   NOT NULL,
    "parkedVehicle" int   NOT NULL,
    "bridge" int   NOT NULL,
    "cliffBank" int   NOT NULL,
    "debris" int   NOT NULL,
    "ditch" int   NOT NULL,
    "fence" int   NOT NULL,
    "flatHill" varchar(50)   NOT NULL,
    "guardRail" int   NOT NULL,
    "building" int   NOT NULL,
    "kerb" int   NOT NULL,
    "objectThrown" int   NOT NULL,
    "otherObject" int   NOT NULL,
    "overBank" int   NOT NULL,
    "phoneBox" int   NOT NULL,
    "postOrPole" int   NOT NULL,
    "slipOrFlood" int   NOT NULL,
    "strayAnimal" int   NOT NULL,
    "trafficIsland" int   NOT NULL,
    "trafficSign" int   NOT NULL,
    "tree" int   NOT NULL,
    "river" int   NOT NULL,
    "light" varchar(50)   NOT NULL,
    "streetLight" varchar(50)   NOT NULL,
    "weatherRain" varchar(50)   NOT NULL,
    "weatherWind" varchar(50)   NOT NULL,
    CONSTRAINT "pk_Crashes" PRIMARY KEY (
        "crashID"
     )
);

